parameters:
  setup.class: Xtrasmal\TacticianBundle\Setup\Setup
  tactician.commandbus.class: League\Tactician\CommandBus

services:
    tactician.commandbus.factory:
        class: %setup.class%
    tactician.commandbus:
        class:   %tactician.commandbus.class%
        factory: ["@tactician.commandbus.factory", create]