language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  matrix:
    - SYMFONY_VERSION="3.4.*"
    - SYMFONY_VERSION="4.4.*"
    - SYMFONY_VERSION="5.2.*"

matrix:
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" DOCTRINE="false"

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update || true
  - if [ "$DOCTRINE" == "false" ]; then composer remove league/tactician-doctrine --dev --no-update; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi

install: composer update $COMPOSER_FLAGS --prefer-dist --no-interaction

script: ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
